### ISSUE TITLE
Proposal: alternative way to build Docker image when original Dockerfile is too old to build

### ISSUE THREAD

**Issue by junjun-zhang** [ICGC-TCGA-PanCancer/pcawg_delly_workflow#15]
## Motivation
We have encountered problems building Docker image in multiple PCAWG dockerized workflows, such as Delly (this repo) and [Sanger](https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker).

The problem is often caused by the fact the original Dockerfiles are based on old base images (such as Ubuntu 14.04) and many dependent libraries were not pinned to particular versions (or stable referencing/versioning was simply not available). As time goes on, it will be more likely to fail when building docker image using original Dockerfile (with necessary patches).

## Proposal
Instead of patching original Dockerfile and using it to build image, an alternative is to use a new Dockerfile which starts from a latest known working version of the docker image as base image. In the new Dockerfile, we simply only include actions needed for fixing bugs, eg, copy an patch script to the right place, installation a specific version of library etc.

Here is one such new Dockerfile:
```
FROM quay.io/pancancer/pcawg_delly_workflow:feature_gosu_and_icgc_portal
USER root
COPY scripts/run_seqware_workflow.pl /usr/bin/
COPY scripts/start.sh /start.sh
RUN chmod a+rx /start.sh
USER seqware
```
In this example, the bug fix involves updating two scripts. We can simply build a new image using the old version of image as base, then copy the updated version of the scripts into it.

This should work well and we have successfully tested the approach when fixing bugs in three different PCAWG workflows.

There is one caveat, if we simply overwrite original dockerfile with this simple one, how do we know what's going on? Particularly, a user will not easily know what components are needed in a pcawg workflow? In order to preserve provenance how full docker image was build, we can keep all version of the Dockerfiles instead of overwrite previous one. Although git repo does allow older version to be retrieved, it's not obvious and convenient for an ordinary user.

So, here is the proposal when we need to build a new version of image:
* start a new git branch named as `<tag>`
* create a new dockerfile, name it as `Dockerfile-<tag>`, add it to git repo
* remove existing dockerfile `Dockerfile` (this should be just a symbolic link, except for the first time adopting this proposal, in this case we need to copy the `Dockerfile` to `Docker-<old_tag>` and check it in git repo)
* create a symbolic link linking `Dockerfile-<tag>` to `Dockerfile`

In such way, we can easily figure out the full evolution of the `Dockerfile`. Additionally, Quay will be able to automatically build new docker images as before.

## Testing
Testing is essential to make sure `fixed` Docker image works as expected. Typical PCAWG workflows are complex, quick testing is hard or not even possible. The ICGC DCC Bioinformatics team will manually test the new image using real data as input, only when test passes, we will proceed with merge and release.

**Comment by junjun-zhang** [comment]
I'd like to add that if a fix or improvement does not involve any change in Dockerfile (ie, no need to build new docker image), such as updating CWL descriptor itself, we will then simply not to touch any docker files.

The only thing need to sort out is that when we create a new release for the above fix/improvement, the docker image tag will remain the same but the code release version will be advanced. This ends with release version being different than docker image tag. Here is the proposal for this scenario:
- the code release version should follow semantic version: `MAJOR.MINOR.PATCH` (https://semver.org/, although not strictly follow everything).
- docker image tag associated with a particular code release version should consists of two parts only: `MAJOR.MINOR` that matches exactly the corresponding numbers in code release
- whenever a fix/update requires docker image rebuild we will bump up `MINOR` number (may bump up `MAJOR` as need although unlikely)
- whenever a fix/update does not require docker image rebuild, we only bump up `PATCH`

Does this work?

**Comment by denis-yuen** [comment]
That sounds good to me.

**Comment by junjun-zhang** [comment]
OK, thanks for the feedback @denis-yuen. We will move forward with this proposal for this workflow and other PCAWG workflows when ordinary way of docker build fails.

Regarding release tag and docker image tag I thought about it a bit more, since Quay will always build docker images as long as a git branch or git tag is created, and docker image tag always matches branch name or tag name. Without additional work we can't really have a docker image tag with only two parts of the semantic version: `MAJOR.MINOR`.

That's said, I think we can still follow these rules:
* whenever a fix/update requires docker image rebuild we will bump up MINOR number (may bump up MAJOR as need although unlikely)
* whenever a fix/update does not require docker image rebuild, we only bump up PATCH
