### ISSUE TITLE
QUESTION: Is there a requirement for a specific version of cwltool to run this docker container?

### ISSUE THREAD

**Issue by mdperry** [ICGC-TCGA-PanCancer/pcawg_delly_workflow#7]
Hi,

I have been trying to use dockstore to launch this workflow on a VM running in AWS, and when I execute the final dockstore command it keeps throwing an exception:

This is the basic STDERR when it dies (with dockstore --debug turned on):

org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: problems running command: cwltool --non-strict --update /tmp/1471377864034-0/temp1957040716235291870.cwl
        at io.cwl.avro.Utilities.executeCommand(Utilities.java:91)
        at io.cwl.avro.CWL.parseCWL(CWL.java:190)
        at io.github.collaboratory.LauncherCWL.run(LauncherCWL.java:134)
        at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:886)
        at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:837)
        at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:821)
        at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:216)
        at io.dockstore.client.cli.Client.run(Client.java:694)
        at io.dockstore.client.cli.Client.main(Client.java:755)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --non-strict --update /tmp/1471377864034-0/temp1957040716235291870.cwl (Exit value: 2)
        at io.cwl.avro.Utilities.executeCommand(Utilities.java:87)
        ... 8 more

When I cut and paste the command that it objects, and run it manually from the command line cwltool complains that it does not recognized a flag/option named '--update':

ubuntu@ip-172-31-40-214:/mnt/ephemeral$ cwltool --non-strict --update /tmp/1471377864034-0/temp1957040716235291870.cwl
usage: cwltool [-h] [--conformance-test] [--basedir BASEDIR] [--outdir OUTDIR]
               [--no-container]
               [--preserve-environment VAR1,VAR2 [VAR1,VAR2 ...]]
               [--rm-container | --leave-container]
               [--tmpdir-prefix TMPDIR_PREFIX]
               [--tmp-outdir-prefix TMP_OUTDIR_PREFIX | --cachedir CACHEDIR]
               [--rm-tmpdir | --leave-tmpdir]
               [--move-outputs | --leave-outputs | --copy-outputs]
               [--enable-pull | --disable-pull] [--dry-run]
               [--rdf-serializer RDF_SERIALIZER] [--eval-timeout EVAL_TIMEOUT]
               [--print-rdf | --print-dot | --print-pre | --print-deps | --print-input-deps | --pack | --version]
               [--strict | --non-strict] [--verbose | --quiet | --debug]
               [--tool-help] [--relative-deps {primary,cwd}] [--enable-dev]
               [--enable-net] [--custom-net CUSTOM_NET] [--on-error ON_ERROR]
               [--compute-checksum | --no-compute-checksum]
               [workflow] ...
cwltool: error: unrecognized arguments: --update

When I check my version of cwltool that I installed earlier it says:
ubuntu@ip-172-31-40-214:/mnt/ephemeral$ cwltool --version
/usr/local/bin/cwltool 1.0.20160810200423

Is this version too new? or too old? to run with this docker container on Quay.io?

Thanks,

-- Marc Perry

**Comment by denis-yuen** [comment]
Hi, 
Yeah, its a version thing. Newer versions of cwltool lack `--update`, see https://github.com/common-workflow-language/cwltool/issues/87

I think you'll need to use an older version of cwl tool as documented on the "Download CLI Client" page of https://dockstore.org/onboarding ... or a newer version of Dockstore that we have not formally released to production, but can be played around with at https://staging.dockstore.org/

**Comment by mdperry** [comment]
Hi Denis,

Okay, yes, on this page: https://dockstore.org/onboarding 
I found this command: pip install --user cwl-runner cwltool==1.0.20160323212343 schema-salad==1.7.20160316203940 avro==1.7.7
(although I note that as of today's date this has been updated to match the one from the tutorial described below)

And yes that solved the problem with the --update flag.  But I am still unable to get this delly workflow to run on AWS using the dockstore CLI.  And on two other authoritative pages I found the instructions specify two different versions of cwltool.

For example on Brian's tutorial from late July, 2016: https://github.com/ga4gh/dockstore/wiki/Dockstore-New-Developer-Tutorial

It states: pip install cwl-runner cwltool==1.0.20160316150250 schema-salad==1.7.20160316150109 avro==1.7.7

And on the dockstore repo itself: 

It states: pip install --user cwl-runner cwltool==1.0.20160712154127 schema-salad==1.14.20160708181155 avro==1.8.1

You mentioned the staging version of dockstore, is that your recommendation, to download the CLI from there?

Thanks,

-- Marc

**Comment by denis-yuen** [comment]
Hi, 

No, I would recommend sticking with the production version since the new issue that you are running into does not seem to be affected by different dockstore versions. I think you would only want the new version if you wanted to play with CWL 1.0 or another new feature that we happen to support. 

In other words, it depends on what you're trying to do.
